version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: csv_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csv_db
    ports:
      - "3306:3306"
    volumes:
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
